---
name: tech_foul
on:
  push:
    branches: [main, master]
  schedule:
    - cron: 0 0 * * *
  pull_request:
    types: [opened, reopened, edited, ready_for_review]

jobs:
  tech_foul:
    runs-on: ubuntu-latest
    steps:
      - name: Clone and check out repository
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: '16.14.10'
        run: npm ci
        run: npm test
      - name: Lint
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
